# Generated by Django 4.2.5 on 2023-09-21 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('detalle', models.CharField(max_length=45)),
                ('codBanco', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conceptos_Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Conceptos_Otros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('A', 'A'), ('I', 'I')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CuentasBancarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCue', models.CharField(max_length=20)),
                ('tipoCue', models.CharField(choices=[('CC', 'CC'), ('CA', 'CA')], max_length=2)),
                ('pago', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=2)),
                ('estado', models.CharField(choices=[('A', 'A'), ('I', 'I')], max_length=2)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.bancos')),
            ],
        ),
        migrations.CreateModel(
            name='Cuotas_Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=45)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('A', 'A'), ('I', 'I')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=7, unique=True)),
                ('fecha', models.DateField()),
                ('inmueble', models.IntegerField()),
                ('tercero', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=45)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fechaPago', models.DateField()),
                ('impresion', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parametrización',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=15)),
                ('razsoc', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=60)),
                ('ciudad', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=10)),
                ('plazo', models.IntegerField()),
                ('imprevisto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('intmor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=45)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=16)),
                ('intmor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('imprevistos', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estados', models.CharField(choices=[('A', 'A'), ('I', 'I'), ('H', 'H')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Terceros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numDoc', models.CharField(max_length=45)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('telmov', models.CharField(max_length=12)),
                ('tipDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Tar_Inm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('id_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.inmuebles')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.tarifas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recaudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('deuda', models.DecimalField(decimal_places=2, max_digits=14)),
                ('documento', models.CharField(max_length=7)),
                ('nota', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('E', 'E'), ('P', 'P'), ('C', 'C')], max_length=1)),
                ('Inmuebles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.inmuebles')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Otro_inm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.conceptos_otros')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.inmuebles')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalles', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('P', 'P'), ('A', 'A')], max_length=2)),
                ('idInmueble', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conjunto.inmuebles')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notas_novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.CharField(max_length=150)),
                ('inmueble', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conjunto.inmuebles')),
                ('novedad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conjunto.novedades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Multas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('inmuelble', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conjunto.inmuebles')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inm_Ter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(max_length=40)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('A', 'A'), ('I', 'I')], max_length=2)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.inmuebles')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.terceros')),
            ],
        ),
        migrations.CreateModel(
            name='Ext_Inm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cuota_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.cuotas_extras')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.inmuebles')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.IntegerField(unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pago', models.CharField(choices=[('EF', 'EF'), ('CF', 'CF'), ('TA', 'TA'), ('OB', 'OB')], max_length=40)),
                ('numero', models.CharField(max_length=20)),
                ('tipTar', models.CharField(choices=[('CC', 'CC'), ('CD', 'CD')], max_length=2)),
                ('numAuth', models.CharField(max_length=6)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.bancos')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.cuentasbancarias')),
                ('recaudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.recaudos')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.IntegerField(unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pago', models.CharField(max_length=20)),
                ('tipTar', models.CharField(choices=[('C', 'C'), ('D', 'C')], max_length=2)),
                ('numaut', models.CharField(max_length=6)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.bancos')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.cuentasbancarias')),
            ],
        ),
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('AD', 'AD'), ('MU', 'MU'), ('CE', 'CE'), ('OT', 'OT'), ('PA', 'PA'), ('IN', 'PA')], max_length=10)),
                ('documento', models.CharField(max_length=7)),
                ('fecha', models.DateField()),
                ('detalle', models.CharField(max_length=45)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('naturaleza', models.CharField(choices=[('D', 'D'), ('C', 'C')], max_length=12)),
                ('docori', models.CharField(max_length=20)),
                ('docru', models.CharField(max_length=10)),
                ('marcru', models.CharField(max_length=45)),
                ('estado', models.CharField(choices=[('A', 'A'), ('P', 'P'), ('C', 'C')], max_length=1)),
                ('idInmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.inmuebles')),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=8)),
                ('tipo', models.CharField(choices=[('I', 'I'), ('U', 'U'), ('D', 'D')], max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
