# Generated by Django 4.2.5 on 2023-09-22 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conjunto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrización',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('nota', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('A', 'A'), ('C', 'C')], max_length=2)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.conceptos_gastos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
