# Generated by Django 4.2.5 on 2023-09-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0002_alter_parametrización_email_gastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tar_inm',
            name='fechafin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tar_inm',
            name='fechainicio',
            field=models.DateTimeField(),
        ),
    ]
