# Generated by Django 4.2.5 on 2023-09-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0003_alter_tar_inm_fechafin_alter_tar_inm_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tar_inm',
            name='fechafin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tar_inm',
            name='fechainicio',
            field=models.DateField(),
        ),
    ]
