# Generated by Django 4.2.5 on 2023-09-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0005_alter_facturas_inmueble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_gas',
            name='tipTar',
            field=models.CharField(choices=[('C', 'C'), ('D', 'D')], max_length=2),
        ),
    ]
