# Generated by Django 4.2.5 on 2023-09-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0006_alter_detalle_gas_tiptar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas_novedad',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjunto.inmuebles'),
        ),
    ]
