# Generated by Django 4.2.5 on 2023-09-26 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0007_alter_notas_novedad_inmueble'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multas',
            name='inmuelble',
        ),
        migrations.AddField(
            model_name='multas',
            name='inmueble',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conjunto.inmuebles'),
            preserve_default=False,
        ),
    ]
