# Generated by Django 4.2.5 on 2023-09-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='document',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
