# Generated by Django 4.2.5 on 2023-09-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emailVerificado',
            field=models.BooleanField(default=False),
        ),
    ]
