# Generated by Django 4.2.5 on 2023-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser_emailverificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='esVerificadoTelefono',
            field=models.BooleanField(default=False),
        ),
    ]
