# Generated by Django 4.2.5 on 2023-09-27 19:23

from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_customuser_esverificadotelefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
         migrations.AddField(
            model_name='customuser',
            name='fecact',
            field=models.DateField(default=date.today()),  # Establece la fecha actual como valor predeterminado
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
